parameters:
#    ns_ace.example.class: NS\AceBundle\Example

services:
    ns_ace.form.entity_create:
        class: NS\AceBundle\Form\EntityOrCreateType
        tags:
            - { name: form.type, alias: entity_create }
    ns_ace.form.iconbutton_extension:
      class: NS\AceBundle\Form\Extensions\ButtonTypeExtension
      tags:
        - { name: form.type_extension, alias: submit }

    ns_ace.form.iconbutton:
      class: NS\AceBundle\Form\IconButtonType
      tags:
        - { name: form.type, alias: iconbutton }

    ns_ace.access_denied:
      class: NS\AceBundle\Listener\AccessDenied
      arguments: [ @twig ]
      tags:
        - { name: kernel.event_listener, event: security.kernel_response, method: handle }

    ns_ace.form.type.switch:
      class: NS\AceBundle\Form\SwitchType
      tags:
        - { name: form.type, alias: switch }

    ns_ace.form.type.slider:
      class: NS\AceBundle\Form\SliderType
      tags:
        - { name: form.type, alias: slider }

    ns_ace.form.type.acedatepicker:
      class: NS\AceBundle\Form\DatePickerType
      arguments: [ @ns_ace.date_format_converter ]
      tags:
        - { name: form.type, alias: acedatepicker }
        
    ns_ace.form.type.acedaterange:
      class: NS\AceBundle\Form\DateRangeType
      arguments: [ @ns_ace.date_format_converter ]
      tags:
        - { name: form.type, alias: acedaterange }

    ns_ace.form.type.acedatetimepicker:
      class: NS\AceBundle\Form\DateTimePickerType
      arguments: [ @ns_ace.date_format_converter ]
      tags:
        - { name: form.type, alias: acedatetime }

    ns_ace.form.type.fileupload:
      class: NS\AceBundle\Form\FileUploadType
      tags:
        - { name: form.type, alias: fileupload }

    ns_ace.form.type.autocompleter:
      class: NS\AceBundle\Form\AutocompleterType
      arguments: [ @doctrine.orm.entity_manager, @router ]
      tags:
        - { name: form.type, alias: autocompleter }

    ns_ace.form.type.tag:
      class: NS\AceBundle\Form\TagType
      tags:
        - { name: form.type, alias: tag }
        
    ns_ace.form.type.spinner:
      class: NS\AceBundle\Form\SpinnerType
      tags:
        - { name: form.type, alias: spinner }

    ns_ace.form.type.knob:
      class: NS\AceBundle\Form\KnobType
      tags:
        - { name: form.type, alias: knob }

    ns_ace.form.type.masked:
      class: NS\AceBundle\Form\MaskedType
      tags:
        - { name: form.type, alias: masked }
        
    ns_ace.date_format_converter:
      class: NS\AceBundle\Service\DateFormatConverter

    ns_ace.twig.bundle_existence:
      class: NS\AceBundle\Twig\BundleExistence
      arguments: [ @service_container ]
      tags:
        - { name: twig.extension }
          
    ns.twig.ace_extension:
        class: NS\AceBundle\Twig\AceExtension
        arguments: [@service_container]
        tags:
        - { name: twig.extension }
        
#    ns_ace.form.ns_filter_date:
#        class: NS\AceBundle\Filter\Type\DateFilterType
#        arguments: [ @ns_ace.date_format_converter ]
#        tags:
#            - { name: form.type, alias: filter_date }

#    ns_ace.form.ns_filter_date_range:
#        class: NS\AceBundle\Filter\Type\DateRangeFilterType
#        tags:
#            - { name: form.type, alias: filter_date_range }
