imports:
  - { resource: forms.yml }
  - { resource: twig.yml }

services:
  ns_ace.access_denied:
    class: NS\AceBundle\Listener\AccessDenied
    arguments: [ @twig ]
    tags:
      - { name: kernel.event_listener, event: security.kernel_response, method: handle }

  ns_ace.date_format_converter:
    class: NS\AceBundle\Service\DateFormatConverter
