---
services:
  ns_ace.form.entity_create:
    class: NS\AceBundle\Form\EntityOrCreateType
    tags:
      - { name: form.type, alias: entity_create }

  ns_ace.form.iconbutton_extension:
    class: NS\AceBundle\Form\Extensions\ButtonTypeExtension
    tags:
      - { name: form.type_extension, alias: button, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }

  ns_ace.form.hidden_parent_extension:
    class: NS\AceBundle\Form\Extensions\HiddenParentChildExtension
    tags:
      - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

  ns_ace.form.input_addon:
    class: NS\AceBundle\Form\Extensions\InputGroupAddonExtension
    tags:
      - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

  ns_ace.form.label_tooltip:
    class: NS\AceBundle\Form\Extensions\LabelTooltipExtension
    tags:
      - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

  ns_ace.form.type.switch:
    class: NS\AceBundle\Form\SwitchType
    tags:
      - { name: form.type, alias: switch }

  ns_ace.form.type.slider:
    class: NS\AceBundle\Form\SliderType
    tags:
      - { name: form.type, alias: slider }

  ns_ace.form.type.acedatepicker:
    class: NS\AceBundle\Form\DatePickerType
    arguments: [ "@ns_ace.date_format_converter" ]
    tags:
      - { name: form.type, alias: acedatepicker }

  ns_ace.form.type.acedaterange:
    class: NS\AceBundle\Form\DateRangeType
    arguments: [ "@ns_ace.date_format_converter" ]
    tags:
      - { name: form.type, alias: acedaterange }

  ns_ace.form.type.acedatetimepicker:
    class: NS\AceBundle\Form\DateTimePickerType
    arguments: [ "@ns_ace.date_format_converter" ]
    tags:
      - { name: form.type, alias: acedatetime }

  ns_ace.form.type.fileupload:
    class: NS\AceBundle\Form\FileUploadType
    tags:
      - { name: form.type, alias: fileupload }

  ns_ace.form.type.autocompleter:
    class: NS\AceBundle\Form\AutocompleterType
    arguments: [ "@doctrine.orm.entity_manager", "@router" ]
    tags:
      - { name: form.type, alias: autocompleter }

  ns_ace.form.type.entityselect2:
    class: NS\AceBundle\Form\EntitySelect2Type
    arguments: [ "@router" ]
    tags:
      - { name: form.type, alias: select2 }

  ns_ace.form.type.tag:
    class: NS\AceBundle\Form\TagType
    tags:
      - { name: form.type, alias: tag }

  ns_ace.form.type.spinner:
    class: NS\AceBundle\Form\SpinnerType
    tags:
      - { name: form.type, alias: spinner }

  ns_ace.form.type.knob:
    class: NS\AceBundle\Form\KnobType
    tags:
      - { name: form.type, alias: knob }

  ns_ace.form.type.masked:
    class: NS\AceBundle\Form\MaskedType
    tags:
      - { name: form.type, alias: masked }

  ns_ace.form.ns_filter_date:
    class: NS\AceBundle\Filter\Type\DateFilterType
    arguments: [ "@ns_ace.date_format_converter" ]
    tags:
      - { name: form.type }
