services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true
    autoconfigure: true

  NS\AceBundle\:
    resource: '../../'
    exclude:
      - '../../Controller'
      - '../../DependencyInjection'
      - '../../Calendar'

  NS\AceBundle\Controller\CalendarController:
    arguments: [ '@event_dispatcher']
    tags:
      - name: controller.service_arguments

